---
title: "Preliminary Analysis - Negative Strand"
author: "P. Alexander Burnham"
date: "March 14, 2018"
output:
  pdf_document: default
  html_document: default
---


## Set up the Data Sets:
```{r, message=FALSE, warning=FALSE, echo=FALSE}
# Set Working Directory 
setwd("~/AlgerProjects/2015_Bombus_Survey/CSV_Files")

library("ggplot2")
library("dplyr")
library("plyr")

# load in data
Melt <- read.csv("USDAplate1Melt.csv", header=TRUE, stringsAsFactors=FALSE)
Cq <- read.csv("USDAplate1cq.csv", header=TRUE, stringsAsFactors=FALSE)
BombSurv <- read.csv("BombSurvNHBS.csv", header=TRUE, stringsAsFactors=FALSE)

# subset BombSurv:
Bomb <- select(BombSurv, site, Ct_mean, sample_name, species, apiary_near_far, Density, genome_copbee, norm_genome_copbeeHB, target_name)
names(Bomb)[3] <- "Sample"
Bomb <- Bomb[Bomb$target_name=="BQCV",]

# merge data:
Dat <- merge(Melt, Cq)
str(Dat)

# Merge Dat and Bomb
Dat <- merge(Dat, Bomb, all.x=TRUE)
```


## Clean the Data set:
```{r}

DatClean <- Dat
#DatClean <- DatClean[!(DatClean$Cq>33),]
#DatClean <- DatClean[!(DatClean$Melt<78),]
DatClean$Binary <- ifelse(DatClean$Melt > 0, 1, 0)
DatClean$Binary[is.na(DatClean$Binary)] <- 0
 
```


```{r, warning=FALSE}
#ddply summarize:
plotdat <- ddply(DatClean, c("Target", "apiary_near_far"), summarise, 
                        n = length(Binary),
                        mean = mean(Binary, na.rm=TRUE),
                        sd = sqrt(((mean(Binary))*(1-mean(Binary)))/n))

plotdat$apiary_near_far <- ifelse(plotdat$apiary_near_far==0, "No Apiary", "Apiary")
plotdat <- plotdat[-1,]

plot1 <- ggplot(plotdat, aes(x=apiary_near_far, y=mean, fill=Target)) +
  geom_bar(stat="identity", color="black",
           position=position_dodge()) + labs(y="Prevalence", x="Site Type") + geom_errorbar(aes(ymin = mean - sd, ymax = mean + sd, width = 0.2),position=position_dodge(.9))

plot1 + theme_minimal(base_size = 18) + coord_cartesian(ylim = c(0, 1)) + scale_y_continuous(labels = scales::percent) 


```

#Is there a relationship between Neg Strand and Apiary vs no Apiary (p=0.1)
```{r}
DatCleanNeg <- DatClean[DatClean$Target=="BQCV-F",]

fisher.test(DatCleanNeg$Binary, DatCleanNeg$apiary_near_far)
```


